FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libpq-dev ffmpeg \
    poppler-utils tesseract-ocr tesseract-ocr-rus \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY apps/backend ./apps/backend
COPY apps/worker ./apps/worker

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

CMD ["rq", "worker", "--url", "redis://redis:6379", "default"]
